export const ORDER_SESSION_TYPES = {
  CREATED: 'CREATED',
  APPROVED: 'APPROVED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
};

export const PAYMENT_MODES = {
  ONLINE: 'ONLINE',
  CASH: 'CASH',
};

export const PAYMENT_STATUSES = {
  INITIATED: 'INITIATED',
  COMPLETED: 'COMPLETED',
};
